/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.io.File;
import javax.swing.*;
import mavenproject1.ArchivoGAMLP;
import mavenproject1.Main;
import static mavenproject1.Main.*;

public class VentanaPrincipal extends JFrame {
    
    public VentanaPrincipal() {
        initComponents();
        setTitle("Sistema de Escuelas Deportivas GAMLP");
        setSize(500, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo1 = new javax.swing.JLabel();
        btnAgregarEscuela = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        titulo2 = new javax.swing.JLabel();
        btnAgregarCurso = new javax.swing.JButton();
        btnVerListaEscuelas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ej03 = new javax.swing.JButton();
        ej01 = new javax.swing.JButton();
        ej02 = new javax.swing.JButton();
        ej04 = new javax.swing.JButton();
        ej05 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        titulo3 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnLeer = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo1.setText("Gestion GAMLP");

        btnAgregarEscuela.setText("Agregar Escuela");
        btnAgregarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEscuelaActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 0, 51));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        titulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo2.setText("Ejercicios");

        btnAgregarCurso.setText("Inscribir Estudiante");
        btnAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCursoActionPerformed(evt);
            }
        });

        btnVerListaEscuelas.setText("Ver Lista Escuelas");
        btnVerListaEscuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListaEscuelasActionPerformed(evt);
            }
        });

        jButton1.setText("Ver Lista Estudiantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ej03.setText("Buscar escuelas por Distrito");
        ej03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej03ActionPerformed(evt);
            }
        });

        ej01.setText("Ranking Deportes");
        ej01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej01ActionPerformed(evt);
            }
        });

        ej02.setText("Buscar por Apellido");
        ej02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej02ActionPerformed(evt);
            }
        });

        ej04.setText("Mostar cursos con mas ests");
        ej04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej04ActionPerformed(evt);
            }
        });

        ej05.setText("Mostrar cursos disponibles");
        ej05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej05ActionPerformed(evt);
            }
        });

        titulo3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo3.setText("Persistencia");

        btnCrear.setText("Crear Archivo");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnLeer.setText("Cargar Archivo");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Archivo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Archivo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAgregarEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(btnVerListaEscuelas, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 61, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ej01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ej02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ej04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ej03, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(ej05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExit)
                                .addGap(23, 23, 23))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEscuela)
                    .addComponent(btnVerListaEscuelas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCurso)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ej01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ej02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ej03)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ej04)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ej05))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLeer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addGap(30, 30, 30)
                                .addComponent(btnExit))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEscuelaActionPerformed
        // TODO add your BOTON CREAR ESCUELA code here:
        FormularioAgregaEscuela form1 = new FormularioAgregaEscuela();
        form1.setVisible(true);
    }//GEN-LAST:event_btnAgregarEscuelaActionPerformed
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your BOTON EXIT code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCursoActionPerformed
        // TODO add your AGREGA ENTRENADOR code here:
        FormularioAgregaEst form2 = new FormularioAgregaEst();
        form2.setVisible(true);
        
    }//GEN-LAST:event_btnAgregarCursoActionPerformed

    private void btnVerListaEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListaEscuelasActionPerformed
        // TODO add your BOTON LISTAR ESCUELAS code here:
        FormMostrar form0 = new FormMostrar();
        form0.setTexto(Gamlp.mostrarV());
        form0.setVisible(true);
        
    }//GEN-LAST:event_btnVerListaEscuelasActionPerformed

    private void ej03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej03ActionPerformed
        // TODO add your BOTON EJERCICIO 3 code here:
        String input = JOptionPane.showInputDialog(this, "Ingrese el número de distrito:");
        if (input != null) {
            try {
                int distrito = Integer.parseInt(input);
                FormMostrar form = new FormMostrar();
                form.setTexto(Gamlp.mostrarEj03Ventana(distrito));
                form.setVisible(true);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un número válido.");
            }
        }
    }//GEN-LAST:event_ej03ActionPerformed

    private void ej02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej02ActionPerformed
        // TODO add your BOTON EJERCICIO 2 code here:
        String apellido = JOptionPane.showInputDialog(this, "Ingrese el apellido a buscar:");
        if (apellido != null && !apellido.trim().isEmpty()) {
            FormMostrar form = new FormMostrar();
            form.setTexto(Gamlp.mostrarEj02Ventana(apellido));
            form.setVisible(true);
        }

    }//GEN-LAST:event_ej02ActionPerformed

    private void ej04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej04ActionPerformed
        // TODO add your BOTON EJERCICIO 4 code here:
        FormMostrar form = new FormMostrar();
        form.setTexto(Gamlp.mejoresCursosTexto());
        form.setVisible(true);

    }//GEN-LAST:event_ej04ActionPerformed

    private void ej05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej05ActionPerformed
        // TODO add your BOTON EJERCICIO 5 code here:
        try {
            String edadStr = JOptionPane.showInputDialog("Ingrese la edad:");
            int edad = Integer.parseInt(edadStr);
            String genero = JOptionPane.showInputDialog("Ingrese el género (M/F):").toUpperCase();
            FormMostrar form = new FormMostrar();
            form.setTexto(Gamlp.cursosDispoV(edad, genero));
            form.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Entrada inválida.");
        }

    }//GEN-LAST:event_ej05ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your BOTON LISTAR ESTUDS code here:
        FormMostrar form0 = new FormMostrar();
        form0.setTexto(Gamlp.mostrarEst());
        form0.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ej01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej01ActionPerformed
        // TODO add your BOTON EJERCICIO 1 code here:
        FormMostrar form = new FormMostrar();
        form.setTexto(Gamlp.mostrarEj01Ventana());
        form.setVisible(true);
    }//GEN-LAST:event_ej01ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        btnCrear.addActionListener(e -> {
            String ruta = JOptionPane.showInputDialog(this, "Ingrese la ruta del nuevo archivo:", 
                "D:/Nuevo/misEscuelas.dat");
            if (ruta != null && !ruta.trim().isEmpty()) {
                File archivoFisico = new File(ruta);
                boolean reiniciar = false;
                if (archivoFisico.exists()) {
                    int respuesta = JOptionPane.showConfirmDialog(this,
                        "El archivo ya existe.\n¿Deseas borrar su contenido?",
                        "Archivo existente", JOptionPane.YES_NO_OPTION);

                    reiniciar = (respuesta == JOptionPane.YES_OPTION);
                }
                ArchivoGAMLP archivo = new ArchivoGAMLP(ruta);
                archivo.crearArchivoDesdeGUI(ruta, reiniciar);

                String mensaje = archivoFisico.exists()
                    ? (reiniciar ? "Archivo reiniciado exitosamente." : "El archivo ya existía. No se modificó.")
                    : "Archivo creado exitosamente.";
                new FormRutaArchivo(mensaje + "\n" + ruta).setVisible(true);
            }
        });

        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        // TODO add your handling code here:
        btnLeer.addActionListener(e -> {
            String ruta = JOptionPane.showInputDialog(this, "Ingrese la ruta para cargar:",
                "D:/Nuevo/misEscuelas.dat");

            if (ruta != null && !ruta.trim().isEmpty()) {
                try {
                    Main.miArchGuarda.leerNuevo(ruta);
                    new FormRutaArchivo("Archivo cargado correctamente desde:\n" + ruta).setVisible(true);
                } catch (Exception ex) {
                    new FormRutaArchivo("Error al cargar el archivo:\n" + ex.getMessage()).setVisible(true);
                }
            }
        });
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your BOTON GUARDAR code here:
        btnGuardar.addActionListener(e -> {
            String ruta = JOptionPane.showInputDialog(this, "Ingrese la ruta para guardar:",
                "D:/Nuevo/misEscuelas.dat");

            if (ruta != null && !ruta.trim().isEmpty()) {
                try {
                    Main.miArchGuarda.guardarNuevo(
                        ruta,
                        Main.Gamlp.getAllEscuelas(),
                        Main.Gamlp.getNroEscuelas(),
                        Main.Gamlp.getAllDeportes(),
                        Main.Gamlp.getAllContDeportes(),
                        Main.Gamlp.getNroDeportes()
                    );
                    new FormRutaArchivo("Archivo guardado correctamente en:\n" + ruta).setVisible(true);
                } catch (Exception ex) {
                    new FormRutaArchivo("Error al guardar el archivo:\n" + ex.getMessage()).setVisible(true);
                }
            }
        });
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your BOTON ELIMINAR code here:
        String ruta = JOptionPane.showInputDialog(this, 
        "Ingrese la ruta del archivo .dat a eliminar:", 
        "D:/Nuevo/misEscuelas.dat");
        if (ruta != null && !ruta.trim().isEmpty()) {
            File archivo = new File(ruta.trim());
            if (archivo.exists()) {
                int confirm = JOptionPane.showConfirmDialog(this, 
                    "¿Seguro que desea eliminar el archivo?\n" + ruta, 
                    "Confirmar eliminación", 
                    JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    boolean eliminado = archivo.delete();
                    if (eliminado) {
                        JOptionPane.showMessageDialog(this, "Archivo eliminado correctamente.");
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar el archivo.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "El archivo no existe.");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnAgregarEscuela;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnVerListaEscuelas;
    private javax.swing.JButton ej01;
    private javax.swing.JButton ej02;
    private javax.swing.JButton ej03;
    private javax.swing.JButton ej04;
    private javax.swing.JButton ej05;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    // End of variables declaration//GEN-END:variables
}
